CreateConVar( "bsmod_killmove_enable_players", 1, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Enable killmoves on Players." )
CreateConVar( "bsmod_killmove_enable_npcs", 1, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Enable killmoves on NPCs." )
CreateConVar( "bsmod_killmove_enable_teammates", 0, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Enable killmoves on Team Members." )
CreateConVar( "bsmod_killmove_stun_npcs", 1, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Stuns NPCs that are killmovable." )
CreateConVar( "bsmod_killmove_anytime", 0, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Enable killmoving at any time." )
CreateConVar( "bsmod_killmove_anytime_behind", 0, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Enable killmoving at any time from behind." )
CreateConVar( "bsmod_killmove_minhealth", 25, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Minimum health for entities to be killmoved." )
CreateConVar( "bsmod_killmove_time", 5.00, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Killmove time delay." )
CreateConVar( "bsmod_killmove_spawn_healthvial", 0, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Drop a health vial after killmoving." )
CreateConVar( "bsmod_killmove_spawn_healthkit", 0, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Drop a health kit after killmoving." )
CreateConVar( "bsmod_killmove_disable_defaults", 0, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Disable default killmoves in favour of custom ones." )
CreateConVar( "bsmod_killmove_chance", 1, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Denominator for NPC killmovable chance." )
CreateConVar( "bsmod_killmove_player_damage_only", 1, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Player damage will only make targets killmovable." )
CreateConVar( "bsmod_killmove_fovfx", 1, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Enable or disable FOV effects during killmoves." )
CreateConVar( "bsmod_killmove_fov_value", 70, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "FOV value to set during killmoves (0 = disabled)." )
CreateConVar( "bsmod_killmove_lerp_enable", 1, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Enable smooth position/angle lerping during killmoves." )
CreateConVar( "bsmod_killmove_lerp_speed", 250, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Lerp speed in units per second (250 = default RECOMMENDED)." )
CreateConVar( "bsmod_killmove_hide_target_weapons", 1, {FCVAR_SERVER_CAN_EXECUTE, FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY}, "Hide enemy weapons during killmoves." )

CreateClientConVar( "bsmod_killmove_indicator", 1, true, false, "Target indicator: 0=Off, 1=Takedown Prompt, 2=Icon Above Head" )
CreateClientConVar( "bsmod_killmove_key", "", true, false, "Override displayed key for takedown prompt (leave empty to auto-detect)." )
CreateClientConVar( "bsmod_killmove_hide_hud", 1, true, false, "Hide the entire HUD during killmoves." )
CreateClientConVar( "bsmod_killmove_hide_head", 1, true, false, "Hide your head during killmoves (helps with playermodel accessories blocking view)." )
CreateClientConVar( "bsmod_debug_calcview", 0, true, false, "List all CalcView hooks for debugging." )

CreateClientConVar( "bsmod_killmove_thirdperson", 0, true, false, "Show KillMoves in thirdperson." )
CreateClientConVar( "bsmod_killmove_thirdperson_distance", 100, true, false )
CreateClientConVar( "bsmod_killmove_thirdperson_pitch", 25, true, false )
CreateClientConVar( "bsmod_killmove_thirdperson_yaw", -35, true, false )
CreateClientConVar( "bsmod_killmove_thirdperson_offsetup", -15, true, false )
CreateClientConVar( "bsmod_killmove_thirdperson_offsetright", 0, true, false )
CreateClientConVar( "bsmod_killmove_thirdperson_randomyaw", 0, true, false )
